import json
import unicodedata

PATH = r"d:\_EVAN\Dev\EmotionEngine\emotions.json"

NEW = [
    {
        "term": "Toska",
        "origin": "Russian",
        "category": "Sadness/Grief",
        "intensity": "Intense",
        "energy": "Variable",
        "pleasantness": "Low",
        "description": "Vladimir Nabokov: spiritual anguish or a dull ache of the soul—a longing with nothing to long for, nostalgia, or lovesickness at different depths (often bundled as “untranslatable”).",
    },
    {
        "term": "Mamihlapinatapei",
        "origin": "Yaghan (Tierra del Fuego)",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Neutral (Bittersweet)",
        "description": "A meaningful look between two people who both want to initiate something but neither will start first; wordless mutual hesitation (widely cited from Yaghan).",
    },
    {
        "term": "Jayus",
        "origin": "Indonesian",
        "category": "Happiness/Joy",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "A joke so poorly told or unfunny that listeners can’t help but laugh anyway.",
    },
    {
        "term": "Litost",
        "origin": "Czech",
        "category": "Sadness/Grief",
        "intensity": "Intense",
        "energy": "Low",
        "pleasantness": "Very Low",
        "description": "Milan Kundera used this for torment on suddenly seeing one’s own misery or disadvantage (anguish tinged with self-pity).",
    },
    {
        "term": "Tartle",
        "origin": "Scots",
        "category": "Shame/Confusion",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Low",
        "description": "Hesitation when introducing someone because you have momentarily forgotten their name.",
    },
    {
        "term": "Cafuné",
        "origin": "Brazilian Portuguese",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Tenderly running your fingers through someone’s hair; intimate affectionate touch.",
    },
    {
        "term": "Torschlusspanik",
        "origin": "German",
        "category": "Fear/Anxiety",
        "intensity": "Intense",
        "energy": "High",
        "pleasantness": "Low",
        "description": "Literal “gate-closing panic”—fear that life’s opportunities are shrinking as time runs out.",
    },
    {
        "term": "Dépaysement",
        "origin": "French",
        "category": "Confusion",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "Disorientation or strangeness from not being in one’s home country; feeling out-of-place abroad.",
    },
    {
        "term": "Ya'aburnee",
        "origin": "Arabic",
        "category": "Sadness/Grief",
        "intensity": "Intense",
        "energy": "Medium",
        "pleasantness": "Low/High (Conflicted)",
        "description": "Literally “you bury me”—expressing a wish to die before the beloved because living without them would be unbearable.",
    },
    {
        "term": "Duende",
        "origin": "Spanish",
        "category": "Happiness/Joy",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "High",
        "description": "A work of art’s mysterious power to move someone deeply (from folkloric spirits to flamenco and poetry).",
    },
    {
        "term": "Backpfeifengesicht",
        "origin": "German",
        "category": "Anger/Boundaries",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Low",
        "description": "Humorous compound: a face that looks badly in need of a slap (irritating smugness).",
    },
    {
        "term": "Fernweh",
        "origin": "German",
        "category": "Sadness/Grief",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Low/Neutral",
        "description": "Aching longing for faraway places—even ones you have never visited (counterpart to homesickness).",
    },
    {
        "term": "Gigil",
        "origin": "Filipino",
        "category": "Happiness/Joy",
        "intensity": "Soft",
        "energy": "Medium",
        "pleasantness": "High",
        "description": "The urge to pinch, squeeze, or fuss over something unbearably cute.",
    },
    {
        "term": "Forelsket",
        "origin": "Norwegian",
        "category": "Happiness/Joy",
        "intensity": "Medium",
        "energy": "High",
        "pleasantness": "Very High",
        "description": "Euphoria of first falling in love (often described as untranslatable in English).",
    },
    {
        "term": "Retrouvailles",
        "origin": "French",
        "category": "Happiness/Joy",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Joy of meeting someone again after a long separation; sweetness of reunion.",
    },
    {
        "term": "Ras-le-bol",
        "origin": "French",
        "category": "Anger, Apathy, and Hatred",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Low",
        "description": "Colloquial “fed up”—accumulated frustration boiling over (literally “bowl full to the brim”).",
    },
    {
        "term": "Mágoa",
        "origin": "Portuguese",
        "category": "Sadness/Grief",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Low",
        "description": "Hurt—physical or emotional—often encompassing sorrow, grief, or wounded feelings.",
    },
    {
        "term": "Desabafar",
        "origin": "Portuguese",
        "category": "Nonspecific",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "Needing to vent problems or release distress—talking, moving, or acting it out to feel relief.",
    },
    {
        "term": "Apaixonar",
        "origin": "Portuguese",
        "category": "Happiness/Joy",
        "intensity": "Soft",
        "energy": "Medium",
        "pleasantness": "High",
        "description": "The experience of falling in love or becoming passionately attached.",
    },
    {
        "term": "Koselig",
        "origin": "Norwegian",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Cosy togetherness broader than “hygge”—people, news, or settings that feel warm and pleasantly snug.",
    },
    {
        "term": "Lagom",
        "origin": "Swedish",
        "category": "Happiness/Contentment",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Neutral/High",
        "description": "Just the right amount—not too much, not too little; balanced sufficiency.",
    },
    {
        "term": "Flâner",
        "origin": "French",
        "category": "Peace/Solitude",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Strolling without goal, observing city life and atmosphere (flâneur activity as mood).",
    },
    {
        "term": "Meraki",
        "origin": "Greek",
        "category": "Happiness/Joy",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "High",
        "description": "Doing something with wholehearted care, creativity, and a piece of yourself left in the work.",
    },
    {
        "term": "Komorebi",
        "origin": "Japanese",
        "category": "Peace/Solitude",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Sunlight filtered through leaves; scenic calm often tied to quiet aesthetic feeling.",
    },
    {
        "term": "Pena ajena",
        "origin": "Spanish",
        "category": "Shame/Confusion",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Low",
        "description": "Embarrassment felt on someone else’s behalf (“secondhand cringe”).",
    },
    {
        "term": "Boketto",
        "origin": "Japanese",
        "category": "Apathy/Depression",
        "intensity": "Soft",
        "energy": "Very Low",
        "pleasantness": "Neutral",
        "description": "Gazing vacantly into the distance without thinking—mind-absent resting of the eyes.",
    },
    {
        "term": "Schnapsidee",
        "origin": "German",
        "category": "Confusion",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "A plan or idea so absurd it might only have come from drunkenness (literally “schnapps idea”).",
    },
    {
        "term": "Slampadato",
        "origin": "Italian",
        "category": "Happiness/Joy",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Neutral",
        "description": "The orange-tinged skin tone from overuse of tanning salons (Babbel / humorous “untranslatable”).",
    },
    {
        "term": "Feestvarken",
        "origin": "Dutch",
        "category": "Social Connection",
        "intensity": "Medium",
        "energy": "High",
        "pleasantness": "High",
        "description": "“Party pig”—the guest in whose honor a celebration is thrown.",
    },
    {
        "term": "Linslus",
        "origin": "Swedish",
        "category": "Social Comparison",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "Someone who always wants to be in front of the camera (attention-seeker around lenses).",
    },
    {
        "term": "Hè hè",
        "origin": "Dutch",
        "category": "Happiness/Contentment",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Expressive sigh of relief after a long or tiring day.",
    },
    {
        "term": "Sonder",
        "origin": "English (coined, Dictionary of Obscure Sorrows)",
        "category": "Social Connection",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Neutral",
        "description": "John Koenig: realization that each passerby has an inner life as vivid and complex as your own.",
    },
    {
        "term": "Watashiato",
        "origin": "English (coined, Dictionary of Obscure Sorrows)",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Neutral",
        "description": "John Koenig: curiosity about what impact you have had on others’ lives—wondering which forgotten moments changed their stories.",
    },
    {
        "term": "Etterath",
        "origin": "English (coined, Dictionary of Obscure Sorrows)",
        "category": "Sadness/Grief",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Neutral/Low",
        "description": "John Koenig: hollow emptiness after a huge ordeal ends—relief mixed with missing the mission that structured you.",
    },
]

NEW2 = [
    {
        "term": "Sisu",
        "origin": "Finnish",
        "category": "Fear/Anxiety",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "Grit to keep going through hardship without drama—stubborn courage when endurance matters more than comfort.",
    },
    {
        "term": "Ubuntu",
        "origin": "Nguni Bantu",
        "category": "Social Connection",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Humanity toward others; the moral sense that personhood is woven from community (“I am because we are”).",
    },
    {
        "term": "Voorpret",
        "origin": "Dutch",
        "category": "Happiness/Joy",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "High",
        "description": "Pleasure taken in anticipating a forthcoming event—pre-fun before the party begins.",
    },
    {
        "term": "Iktsuarpok",
        "origin": "Inuktitut",
        "category": "Anxiety",
        "intensity": "Soft",
        "energy": "Medium",
        "pleasantness": "Neutral",
        "description": "Restlessness that pulls you outside again and again to see if someone is coming—expectant suspense.",
    },
    {
        "term": "Fremdscham",
        "origin": "German",
        "category": "Shame/Confusion",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Low",
        "description": "Vicarious embarrassment; cringing on someone else’s behalf (overlap with Spanish pena ajena).",
    },
    {
        "term": "Gökotta",
        "origin": "Swedish",
        "category": "Peace/Solitude",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Waking early to go outside and listen to birdsong—dawn-quiet as a mood.",
    },
    {
        "term": "Weltschmerz",
        "origin": "German",
        "category": "Sadness/Grief",
        "intensity": "Medium",
        "energy": "Low",
        "pleasantness": "Low",
        "description": "Melancholy about the world’s flaws or cruelty—romantic world-weariness rather than personal grief alone.",
    },
    {
        "term": "Han",
        "origin": "Korean",
        "category": "Sadness/Grief",
        "intensity": "Intense",
        "energy": "Low",
        "pleasantness": "Very Low",
        "description": "Cultural complex of sorrow, resentment, and unfinished grief from collective injustice—often glossed as national heartache.",
    },
    {
        "term": "Greng jai",
        "origin": "Thai",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Neutral",
        "description": "Hesitation to impose or inconvenience others, or worry about causing someone else to lose face or trouble.",
    },
    {
        "term": "Zhaghzhagh",
        "origin": "Persian (Farsi)",
        "category": "Fear/Anxiety",
        "intensity": "Soft",
        "energy": "High",
        "pleasantness": "Low",
        "description": "Chattering of the teeth from cold, rage, or anxiety—a bodily marker of stirred-up feeling.",
    },
    {
        "term": "Verschlimmbesserung",
        "origin": "German",
        "category": "Confusion",
        "intensity": "Medium",
        "energy": "Medium",
        "pleasantness": "Low",
        "description": "Making something worse while trying to improve it—failed fix that adds new problems.",
    },
    {
        "term": "Yugen",
        "origin": "Japanese",
        "category": "Happiness/Joy",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Aesthetic sense of subtle, profound depth and mystery—beauty too deep for plain statement.",
    },
    {
        "term": "Shinrin-yoku",
        "origin": "Japanese",
        "category": "Peace/Solitude",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "“Forest bathing”—immersing in woodland atmosphere for restorative calm (often counted as an untranslatable wellness idea).",
    },
    {
        "term": "Kummerspeck",
        "origin": "German",
        "category": "Sadness/Grief",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "Low",
        "description": "Humorous compound: literal “grief bacon”—weight gained from emotional overeating during stress or sorrow.",
    },
    {
        "term": "Sobremesa",
        "origin": "Spanish",
        "category": "Social Connection",
        "intensity": "Soft",
        "energy": "Low",
        "pleasantness": "High",
        "description": "Leisurely tabletop time after eating—conversation and presence lingering once the meal is done.",
    },
    {
        "term": "Mångata",
        "origin": "Swedish",
        "category": "Peace/Solitude",
        "intensity": "Soft",
        "energy": "Very Low",
        "pleasantness": "High",
        "description": "Moonlight’s rippled road across water—a still, enchanted nightscape feeling.",
    },
]

# NFC-normalize + casefold for dedup against existing + within batch
def key(t):
    return unicodedata.normalize("NFC", t.strip()).casefold()


def main():
    with open(PATH, encoding="utf-8") as f:
        data = json.load(f)

    have = {key(o["term"]) for o in data if isinstance(o, dict) and "term" in o}
    added = 0
    seen_new = set()
    for o in NEW + NEW2:
        k = key(o["term"])
        if k in have or k in seen_new:
            continue
        seen_new.add(k)
        have.add(k)
        data.append(o)
        added += 1

    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print("appended", added, "entries; total", len(data))


if __name__ == "__main__":
    main()
